### ISSUE TITLE
Database not available for non chinese researchers

### ISSUE THREAD

**Issue by chavizz** [JingchunCheng/All-Age-Faces-Dataset#1]
Hello,

Thanks for providing this dataset first of all. Currently the dataset is only available for people with chinese phone number. Unfortunately we can't get access to baidu drive without an account. Would it be possible to upload the data to google drive? 

Thank you!

**Comment by JingchunCheng** [comment]
Sorry that we have not noticed this.
We added a dropbox link, you can download via that one.

**Comment by gonelove31** [comment]
Just tried https://baidufast.com/ and it actually works pretty well. They give for free. Honestly, that’s pretty cheap compared to most of these services.
